version: "3"

services:

  keycloak-1:

    image: "yourdesiredimage/image:latest"
    command: start-dev
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: mariadb
      KC_DB_URL_HOST: 192.168.1.1
      KC_DB_URL_DATABASE: KEYCLOAK
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
      KC_LOG_LEVEL: INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
      KC_HTTPS_CERTIFICATE_FILE: /etc/ssl/certs/mycert.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/ssl/certs/mycert.key
      JGROUPS_DISCOVERY_EXTERNAL_IP: 192.168.1.2
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    volumes:
      - ./data_themes:/opt/keycloak/themes/
      - ./cert/mycert.crt:/etc/ssl/certs/mycert.crt
      - ./cert/mycert.key:/etc/ssl/certs/mycert.key
    restart: always
    ports:
      - "8080:8080"
      - "7600:7600"
      - "8443:8443"
